steps:
  - name: 'python:3.8-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===Starting Python Application Build==="
        'python:3.8-slim' hello.py
        echo "===Python Application Build Completed==="

options:
  logging: CLOUD_LOGGING_ONLY
  #logging: NONE