steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===Starting Python Application Build==="
        python hello.py
        echo "===Python Application Build Completed==="

options:
  logging: CLOUD_LOGGING_ONLY
  #logging: NONE

timeout: "20s"
